# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_anapencere(object):
    def setupUi(self, anapencere):
        anapencere.setObjectName("anapencere")
        anapencere.resize(480, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/start.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        anapencere.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(anapencere)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_pass_to_secondpage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pass_to_secondpage.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pass_to_secondpage.setFont(font)
        self.pushButton_pass_to_secondpage.setObjectName("pushButton_pass_to_secondpage")
        self.gridLayout.addWidget(self.pushButton_pass_to_secondpage, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButton_pass_to_third_page = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pass_to_third_page.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pass_to_third_page.setFont(font)
        self.pushButton_pass_to_third_page.setObjectName("pushButton_pass_to_third_page")
        self.gridLayout.addWidget(self.pushButton_pass_to_third_page, 2, 0, 1, 1)
        anapencere.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(anapencere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        anapencere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(anapencere)
        self.statusbar.setObjectName("statusbar")
        anapencere.setStatusBar(self.statusbar)

        self.retranslateUi(anapencere)
        QtCore.QMetaObject.connectSlotsByName(anapencere)

    def retranslateUi(self, anapencere):
        _translate = QtCore.QCoreApplication.translate
        anapencere.setWindowTitle(_translate("anapencere", "Çok Pencreli Uygulama"))
        self.pushButton_pass_to_secondpage.setText(_translate("anapencere", "2. pencereyi aç"))
        self.label.setText(_translate("anapencere", "Ana Pencere"))
        self.pushButton_pass_to_third_page.setText(_translate("anapencere", "3. pencereyi aç"))
import keyboard_rc
import start_rc
import stop_rc
import turnoff_rc
