# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datetimeedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.t_edit = QtWidgets.QTimeEdit(self.centralwidget)
        self.t_edit.setGeometry(QtCore.QRect(100, 200, 193, 109))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_edit.sizePolicy().hasHeightForWidth())
        self.t_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.t_edit.setFont(font)
        self.t_edit.setCalendarPopup(True)
        self.t_edit.setObjectName("t_edit")
        self.dt_edit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dt_edit.setGeometry(QtCore.QRect(320, 240, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dt_edit.setFont(font)
        self.dt_edit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.dt_edit.setMinimumDate(QtCore.QDate(1920, 9, 14))
        self.dt_edit.setCalendarPopup(True)
        self.dt_edit.setObjectName("dt_edit")
        self.btn_tarih = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tarih.setGeometry(QtCore.QRect(80, 340, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_tarih.setFont(font)
        self.btn_tarih.setObjectName("btn_tarih")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 20, 451, 111))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.d_edit_start = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_edit_start.sizePolicy().hasHeightForWidth())
        self.d_edit_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.d_edit_start.setFont(font)
        self.d_edit_start.setCalendarPopup(True)
        self.d_edit_start.setObjectName("d_edit_start")
        self.horizontalLayout.addWidget(self.d_edit_start)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.d_edit_end = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_edit_end.sizePolicy().hasHeightForWidth())
        self.d_edit_end.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.d_edit_end.setFont(font)
        self.d_edit_end.setCalendarPopup(True)
        self.d_edit_end.setObjectName("d_edit_end")
        self.horizontalLayout.addWidget(self.d_edit_end)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_tarih.setText(_translate("MainWindow", "Tarih Seç"))
