# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qsqldatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/database.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#MainWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.364, x2:1, y2:0.79, stop:0 rgba(18, 139, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"#MainWindow QGroupBox{\n"
"border : 1px solid #c6c6c6 ;\n"
"border-radius :5px ;\n"
"}\n"
"\n"
"#groupBox {\n"
"border :none ;\n"
"background-color : qlineargradient(spread:pad, x1:1, y1:0.613727, x2:0, y2:0.244, stop:0 rgba(18, 0, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"#groupBox_2 {\n"
"background-color : #fff\n"
"}\n"
"\n"
"#MainWindow QPushButton{\n"
"border: 1px solid rgb(127,127,127);\n"
"border-radius :5px ;\n"
"background-color:#fff;\n"
"padding :4px 8px ;\n"
"text-align:center;\n"
"}\n"
"\n"
"#MainWindow QPushButton:hover{\n"
"color:#fff;\n"
"background-color:#00aaff;\n"
"\n"
"}\n"
"\n"
"#MainWindow QPushButton:pressed{\n"
"padding-left:15px ;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/database.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(177, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_get_path = QtWidgets.QPushButton(self.widget)
        self.pushButton_get_path.setMinimumSize(QtCore.QSize(150, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_get_path.setIcon(icon1)
        self.pushButton_get_path.setObjectName("pushButton_get_path")
        self.gridLayout_2.addWidget(self.pushButton_get_path, 0, 2, 1, 1)
        self.pushButton_save_data = QtWidgets.QPushButton(self.widget)
        self.pushButton_save_data.setMinimumSize(QtCore.QSize(120, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save_data.setIcon(icon2)
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.gridLayout_2.addWidget(self.pushButton_save_data, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 4, 1, 1)
        self.pushButton_get_data = QtWidgets.QPushButton(self.widget)
        self.pushButton_get_data.setMinimumSize(QtCore.QSize(100, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_get_data.setIcon(icon3)
        self.pushButton_get_data.setObjectName("pushButton_get_data")
        self.gridLayout_2.addWidget(self.pushButton_get_data, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QSqlDatabase"))
        self.label_2.setText(_translate("MainWindow", "Get and Show data from mysql database"))
        self.pushButton_get_path.setText(_translate("MainWindow", "Select Save Path"))
        self.pushButton_save_data.setText(_translate("MainWindow", "Save Data"))
        self.pushButton_get_data.setText(_translate("MainWindow", "Get Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Adı"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Soyadı"))
import resource_rc
