# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 360)
        MainWindow.setStyleSheet("#btn_getir{\n"
"\n"
"color : rgb(200, 105, 10);\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbx_sehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_sehirler.setGeometry(QtCore.QRect(30, 30, 181, 81))
        self.cbx_sehirler.setObjectName("cbx_sehirler")
        self.lbl_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(240, 40, 161, 71))
        self.lbl_sonuc.setText("")
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.btn_getir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_getir.setGeometry(QtCore.QRect(30, 140, 121, 71))
        self.btn_getir.setObjectName("btn_getir")
        self.btn_yukleme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yukleme.setGeometry(QtCore.QRect(160, 140, 131, 71))
        self.btn_yukleme.setObjectName("btn_yukleme")
        self.btn_temizle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_temizle.setGeometry(QtCore.QRect(310, 140, 131, 71))
        self.btn_temizle.setObjectName("btn_temizle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_getir.setText(_translate("MainWindow", "Verileri Getir"))
        self.btn_yukleme.setText(_translate("MainWindow", "Verileri Yükle"))
        self.btn_temizle.setText(_translate("MainWindow", "Temizle"))
