# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_secim = QtWidgets.QPushButton(self.centralwidget)
        self.btn_secim.setGeometry(QtCore.QRect(10, 250, 211, 71))
        self.btn_secim.setObjectName("btn_secim")
        self.lbl_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(20, 330, 181, 221))
        self.lbl_sonuc.setText("")
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        self.gbox_hobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_hobiler.setGeometry(QtCore.QRect(10, 20, 211, 221))
        self.gbox_hobiler.setObjectName("gbox_hobiler")
        self.widget = QtWidgets.QWidget(self.gbox_hobiler)
        self.widget.setGeometry(QtCore.QRect(0, 20, 211, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbx_sinema = QtWidgets.QCheckBox(self.widget)
        self.cbx_sinema.setObjectName("cbx_sinema")
        self.verticalLayout.addWidget(self.cbx_sinema)
        self.cbx_kitap = QtWidgets.QCheckBox(self.widget)
        self.cbx_kitap.setObjectName("cbx_kitap")
        self.verticalLayout.addWidget(self.cbx_kitap)
        self.cbx_spor = QtWidgets.QCheckBox(self.widget)
        self.cbx_spor.setObjectName("cbx_spor")
        self.verticalLayout.addWidget(self.cbx_spor)
        self.gbox_kirtasiye = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_kirtasiye.setGeometry(QtCore.QRect(300, 30, 211, 221))
        self.gbox_kirtasiye.setObjectName("gbox_kirtasiye")
        self.layoutWidget = QtWidgets.QWidget(self.gbox_kirtasiye)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 211, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_defter = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_defter.setObjectName("cb_defter")
        self.verticalLayout_3.addWidget(self.cb_defter)
        self.cb_kalem = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_kalem.setObjectName("cb_kalem")
        self.verticalLayout_3.addWidget(self.cb_kalem)
        self.cb_silgi = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_silgi.setObjectName("cb_silgi")
        self.verticalLayout_3.addWidget(self.cb_silgi)
        self.btn_secim_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_secim_2.setGeometry(QtCore.QRect(290, 260, 211, 71))
        self.btn_secim_2.setObjectName("btn_secim_2")
        self.lbl_sonuc_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sonuc_2.setGeometry(QtCore.QRect(300, 350, 221, 221))
        self.lbl_sonuc_2.setText("")
        self.lbl_sonuc_2.setObjectName("lbl_sonuc_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_secim.setText(_translate("MainWindow", "Seç"))
        self.gbox_hobiler.setTitle(_translate("MainWindow", "hobiler"))
        self.cbx_sinema.setText(_translate("MainWindow", "Sinema"))
        self.cbx_kitap.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cbx_spor.setText(_translate("MainWindow", "Spor"))
        self.gbox_kirtasiye.setTitle(_translate("MainWindow", "kırtasiye"))
        self.cb_defter.setText(_translate("MainWindow", "defter"))
        self.cb_kalem.setText(_translate("MainWindow", "kalem"))
        self.cb_silgi.setText(_translate("MainWindow", "silgi"))
        self.btn_secim_2.setText(_translate("MainWindow", "Seç"))
