# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lw_ogrenciler = QtWidgets.QListWidget(self.centralwidget)
        self.lw_ogrenciler.setGeometry(QtCore.QRect(20, 70, 361, 341))
        self.lw_ogrenciler.setObjectName("lw_ogrenciler")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(410, 70, 141, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ekle = QtWidgets.QPushButton(self.widget)
        self.btn_ekle.setObjectName("btn_ekle")
        self.verticalLayout.addWidget(self.btn_ekle)
        self.btn_duzenle = QtWidgets.QPushButton(self.widget)
        self.btn_duzenle.setObjectName("btn_duzenle")
        self.verticalLayout.addWidget(self.btn_duzenle)
        self.btn_sil = QtWidgets.QPushButton(self.widget)
        self.btn_sil.setObjectName("btn_sil")
        self.verticalLayout.addWidget(self.btn_sil)
        self.btn_asagi = QtWidgets.QPushButton(self.widget)
        self.btn_asagi.setObjectName("btn_asagi")
        self.verticalLayout.addWidget(self.btn_asagi)
        self.btn_yukari = QtWidgets.QPushButton(self.widget)
        self.btn_yukari.setObjectName("btn_yukari")
        self.verticalLayout.addWidget(self.btn_yukari)
        self.btn_sirala = QtWidgets.QPushButton(self.widget)
        self.btn_sirala.setObjectName("btn_sirala")
        self.verticalLayout.addWidget(self.btn_sirala)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_ekle.setText(_translate("MainWindow", "ekle"))
        self.btn_duzenle.setText(_translate("MainWindow", "düzenle"))
        self.btn_sil.setText(_translate("MainWindow", "sil"))
        self.btn_asagi.setText(_translate("MainWindow", "aşağı"))
        self.btn_yukari.setText(_translate("MainWindow", "yukarı"))
        self.btn_sirala.setText(_translate("MainWindow", "sırala"))
        self.btn_exit.setText(_translate("MainWindow", "çıkış"))
