# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_test.setGeometry(QtCore.QRect(210, 230, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_test.setFont(font)
        self.pushButton_test.setObjectName("pushButton_test")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menurenkler = QtWidgets.QMenu(self.menubar)
        self.menurenkler.setObjectName("menurenkler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionyellow = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/yellow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionyellow.setIcon(icon)
        self.actionyellow.setObjectName("actionyellow")
        self.actionblack = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/black.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionblack.setIcon(icon1)
        self.actionblack.setObjectName("actionblack")
        self.actionwhite = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionwhite.setIcon(icon2)
        self.actionwhite.setObjectName("actionwhite")
        self.actionred = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/red.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionred.setIcon(icon3)
        self.actionred.setObjectName("actionred")
        self.menurenkler.addAction(self.actionyellow)
        self.menurenkler.addAction(self.actionblack)
        self.menurenkler.addAction(self.actionwhite)
        self.menurenkler.addAction(self.actionred)
        self.menubar.addAction(self.menurenkler.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_test.setText(_translate("MainWindow", "Kaydet"))
        self.menurenkler.setTitle(_translate("MainWindow", "renkler"))
        self.actionyellow.setText(_translate("MainWindow", "yellow"))
        self.actionyellow.setShortcut(_translate("MainWindow", "Shift+Y"))
        self.actionblack.setText(_translate("MainWindow", "black"))
        self.actionblack.setShortcut(_translate("MainWindow", "Shift+B"))
        self.actionwhite.setText(_translate("MainWindow", "white"))
        self.actionwhite.setShortcut(_translate("MainWindow", "Shift+W"))
        self.actionred.setText(_translate("MainWindow", "red"))
        self.actionred.setShortcut(_translate("MainWindow", "Shift+R"))
import black_rc
import blue_rc
import green_rc
import red_rc
import white_rc
import yellow_rc
