# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 321, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 90, 291, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_name.setObjectName("txt_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_name)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_price = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_price.setObjectName("txt_price")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_price)
        self.btn_kaydet = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_kaydet.setObjectName("btn_kaydet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_kaydet)
        self.pushButton_sil = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sil.setGeometry(QtCore.QRect(360, 220, 93, 28))
        self.pushButton_sil.setObjectName("pushButton_sil")
        self.pushButton_sutun_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sutun_ekle.setGeometry(QtCore.QRect(470, 220, 93, 28))
        self.pushButton_sutun_ekle.setObjectName("pushButton_sutun_ekle")
        self.pushButton_verileri_getir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_verileri_getir.setGeometry(QtCore.QRect(580, 220, 93, 28))
        self.pushButton_verileri_getir.setObjectName("pushButton_verileri_getir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ürün adı"))
        self.label_2.setText(_translate("MainWindow", "fiyat"))
        self.btn_kaydet.setText(_translate("MainWindow", "kaydet"))
        self.pushButton_sil.setText(_translate("MainWindow", "satır sil"))
        self.pushButton_sutun_ekle.setText(_translate("MainWindow", "sutun ekle"))
        self.pushButton_verileri_getir.setText(_translate("MainWindow", "verileri getir"))
