# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 363)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/red/red.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"#centralwidget{\n"
"\n"
"border-image: url(:/arkaplan/1.jpg);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.label_sonuc.setGeometry(QtCore.QRect(150, 130, 71, 91))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_sonuc.setFont(font)
        self.label_sonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sonuc.setObjectName("label_sonuc")
        self.pushButton_artir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_artir.setGeometry(QtCore.QRect(70, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_artir.setFont(font)
        self.pushButton_artir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/blue/blue.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_artir.setIcon(icon1)
        self.pushButton_artir.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_artir.setObjectName("pushButton_artir")
        self.pushButton_eksi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eksi.setGeometry(QtCore.QRect(200, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_eksi.setFont(font)
        self.pushButton_eksi.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.pushButton_eksi.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/black/black.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_eksi.setIcon(icon2)
        self.pushButton_eksi.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_eksi.setObjectName("pushButton_eksi")
        self.pushButton_sil = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sil.setGeometry(QtCore.QRect(330, 20, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sil.setFont(font)
        self.pushButton_sil.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.pushButton_sil.setText("")
        self.pushButton_sil.setIcon(icon2)
        self.pushButton_sil.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_sil.setObjectName("pushButton_sil")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_sonuc.setText(_translate("MainWindow", "0"))
import ikonlar_rc
