# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qpushbutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/turnoff.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_setText = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setText.setGeometry(QtCore.QRect(40, 40, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setText.setFont(font)
        self.pushButton_setText.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_setText.setObjectName("pushButton_setText")
        self.pushButton_icon_text = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon_text.setGeometry(QtCore.QRect(260, 40, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon_text.setFont(font)
        self.pushButton_icon_text.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/keyboard.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_icon_text.setIcon(icon1)
        self.pushButton_icon_text.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon_text.setObjectName("pushButton_icon_text")
        self.pushButton_icon = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon.setGeometry(QtCore.QRect(480, 40, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon.setFont(font)
        self.pushButton_icon.setStyleSheet("")
        self.pushButton_icon.setText("")
        self.pushButton_icon.setIcon(icon1)
        self.pushButton_icon.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon.setObjectName("pushButton_icon")
        self.pushButton_icon_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon_2.setGeometry(QtCore.QRect(620, 40, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon_2.setFont(font)
        self.pushButton_icon_2.setStyleSheet("")
        self.pushButton_icon_2.setText("")
        self.pushButton_icon_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon_2.setObjectName("pushButton_icon_2")
        self.pushButton_icon_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon_3.setGeometry(QtCore.QRect(49, 189, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon_3.setFont(font)
        self.pushButton_icon_3.setStyleSheet("")
        self.pushButton_icon_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon_3.setCheckable(False)
        self.pushButton_icon_3.setObjectName("pushButton_icon_3")
        self.pushButton_icon_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon_4.setGeometry(QtCore.QRect(490, 190, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon_4.setFont(font)
        self.pushButton_icon_4.setStyleSheet("")
        self.pushButton_icon_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon_4.setCheckable(False)
        self.pushButton_icon_4.setObjectName("pushButton_icon_4")
        self.pushButton_icon_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_icon_5.setGeometry(QtCore.QRect(260, 190, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_icon_5.setFont(font)
        self.pushButton_icon_5.setStyleSheet("")
        self.pushButton_icon_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_icon_5.setCheckable(False)
        self.pushButton_icon_5.setObjectName("pushButton_icon_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QPushButton"))
        self.pushButton_setText.setText(_translate("MainWindow", "Başlat"))
        self.pushButton_icon_text.setText(_translate("MainWindow", "Başlat"))
        self.pushButton_icon_3.setText(_translate("MainWindow", "Başlat"))
        self.pushButton_icon_4.setText(_translate("MainWindow", "Başlat"))
        self.pushButton_icon_5.setText(_translate("MainWindow", "Başlat"))
import keyboard_rc
import start_rc
import stop_rc
import turnoff_rc
