# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_show = QtWidgets.QFrame(self.centralwidget)
        self.frame_show.setGeometry(QtCore.QRect(150, 30, 401, 251))
        self.frame_show.setStyleSheet("border-image: url(:/icons/bir.jpg);")
        self.frame_show.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_show.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show.setObjectName("frame_show")
        self.label_aciklama = QtWidgets.QLabel(self.centralwidget)
        self.label_aciklama.setGeometry(QtCore.QRect(90, 330, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_aciklama.setFont(font)
        self.label_aciklama.setFrameShape(QtWidgets.QFrame.Box)
        self.label_aciklama.setText("")
        self.label_aciklama.setObjectName("label_aciklama")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuRenkler = QtWidgets.QMenu(self.menubar)
        self.menuRenkler.setObjectName("menuRenkler")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolBar.setFont(font)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.action_sari = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/yellow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sari.setIcon(icon)
        self.action_sari.setObjectName("action_sari")
        self.actionBeyaz = QtWidgets.QAction(MainWindow)
        self.actionBeyaz.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeyaz.setIcon(icon1)
        self.actionBeyaz.setObjectName("actionBeyaz")
        self.action_yesil = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/green.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_yesil.setIcon(icon2)
        self.action_yesil.setObjectName("action_yesil")
        self.action_siyah = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/black.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_siyah.setIcon(icon3)
        self.action_siyah.setObjectName("action_siyah")
        self.action_kirmizi = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/red.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_kirmizi.setIcon(icon4)
        self.action_kirmizi.setObjectName("action_kirmizi")
        self.action_blue = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/blue.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_blue.setIcon(icon5)
        self.action_blue.setObjectName("action_blue")
        self.menuRenkler.addAction(self.action_sari)
        self.menuRenkler.addAction(self.action_siyah)
        self.menuRenkler.addAction(self.action_kirmizi)
        self.menubar.addAction(self.menuRenkler.menuAction())
        self.toolBar.addAction(self.action_sari)
        self.toolBar.addAction(self.action_yesil)
        self.toolBar.addAction(self.action_siyah)
        self.toolBar.addAction(self.action_kirmizi)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_blue)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBeyaz)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuRenkler.setTitle(_translate("MainWindow", "Renkler"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_sari.setText(_translate("MainWindow", "Sarı"))
        self.action_sari.setShortcut(_translate("MainWindow", "Shift+Y"))
        self.actionBeyaz.setText(_translate("MainWindow", "Beyaz"))
        self.actionBeyaz.setShortcut(_translate("MainWindow", "Shift+W"))
        self.action_yesil.setText(_translate("MainWindow", "Yeşil"))
        self.action_yesil.setShortcut(_translate("MainWindow", "Shift+G"))
        self.action_siyah.setText(_translate("MainWindow", "Siyah"))
        self.action_siyah.setShortcut(_translate("MainWindow", "Shift+B"))
        self.action_kirmizi.setText(_translate("MainWindow", "Kırmızı"))
        self.action_kirmizi.setShortcut(_translate("MainWindow", "Shift+R"))
        self.action_blue.setText(_translate("MainWindow", "Blue"))
        self.action_blue.setToolTip(_translate("MainWindow", "mavi enk"))
        self.action_blue.setShortcut(_translate("MainWindow", "Shift+B"))
import bir_rc
import black_rc
import blue_rc
import green_rc
import red_rc
import white_rc
import yellow_rc
