# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_hobileri_gonder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hobileri_gonder.setGeometry(QtCore.QRect(40, 290, 93, 28))
        self.btn_hobileri_gonder.setObjectName("btn_hobileri_gonder")
        self.lbl_hobiler_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_hobiler_sonuc.setGeometry(QtCore.QRect(40, 340, 111, 181))
        self.lbl_hobiler_sonuc.setText("")
        self.lbl_hobiler_sonuc.setObjectName("lbl_hobiler_sonuc")
        self.gbox_hobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_hobiler.setGeometry(QtCore.QRect(40, 30, 321, 241))
        self.gbox_hobiler.setObjectName("gbox_hobiler")
        self.widget = QtWidgets.QWidget(self.gbox_hobiler)
        self.widget.setGeometry(QtCore.QRect(60, 20, 141, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbox_sinema = QtWidgets.QCheckBox(self.widget)
        self.cbox_sinema.setObjectName("cbox_sinema")
        self.verticalLayout.addWidget(self.cbox_sinema)
        self.cbox_kitap = QtWidgets.QCheckBox(self.widget)
        self.cbox_kitap.setObjectName("cbox_kitap")
        self.verticalLayout.addWidget(self.cbox_kitap)
        self.cbox_spor = QtWidgets.QCheckBox(self.widget)
        self.cbox_spor.setObjectName("cbox_spor")
        self.verticalLayout.addWidget(self.cbox_spor)
        self.gbox_diller = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_diller.setGeometry(QtCore.QRect(440, 30, 321, 241))
        self.gbox_diller.setObjectName("gbox_diller")
        self.layoutWidget = QtWidgets.QWidget(self.gbox_diller)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 141, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbox_python = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbox_python.setObjectName("cbox_python")
        self.verticalLayout_2.addWidget(self.cbox_python)
        self.cbox_csharp = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbox_csharp.setObjectName("cbox_csharp")
        self.verticalLayout_2.addWidget(self.cbox_csharp)
        self.cbox_javascript = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbox_javascript.setObjectName("cbox_javascript")
        self.verticalLayout_2.addWidget(self.cbox_javascript)
        self.btn_dilleri_gonder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dilleri_gonder.setGeometry(QtCore.QRect(490, 290, 93, 28))
        self.btn_dilleri_gonder.setObjectName("btn_dilleri_gonder")
        self.lbl_diller_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_diller_sonuc.setGeometry(QtCore.QRect(490, 330, 111, 181))
        self.lbl_diller_sonuc.setText("")
        self.lbl_diller_sonuc.setObjectName("lbl_diller_sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_hobileri_gonder.setText(_translate("MainWindow", "PushButton"))
        self.gbox_hobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbox_sinema.setText(_translate("MainWindow", "Sinema"))
        self.cbox_kitap.setText(_translate("MainWindow", "Kitap okuma"))
        self.cbox_spor.setText(_translate("MainWindow", "Spor"))
        self.gbox_diller.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbox_python.setText(_translate("MainWindow", "python"))
        self.cbox_csharp.setText(_translate("MainWindow", "c#"))
        self.cbox_javascript.setText(_translate("MainWindow", "javascript"))
        self.btn_dilleri_gonder.setText(_translate("MainWindow", "PushButton"))
